import type { CSSProperties } from 'react';

import type { ThemeTokens } from '../theme/theme';

export function getWorkspacePageStyles(
  tokens: ThemeTokens,
  options?: {
    compact?: boolean;
    mobile?: boolean;
  },
) {
  const compact = options?.compact ?? false;
  const mobile = options?.mobile ?? false;
  const sectionPadding = mobile ? 16 : compact ? 18 : 22;
  const sectionRadius = mobile ? 20 : 26;

  return {
    stack: {
      display: 'flex',
      flexDirection: 'column',
      gap: compact ? 16 : 20,
      minWidth: 0,
    } satisfies CSSProperties,
    section: {
      display: 'flex',
      flexDirection: 'column',
      gap: compact ? 14 : 16,
      padding: sectionPadding,
      borderRadius: sectionRadius,
      background: tokens.surface,
      minWidth: 0,
    } satisfies CSSProperties,
    sectionHeader: {
      display: 'flex',
      flexDirection: mobile ? 'column' : 'row',
      flexWrap: 'wrap',
      alignItems: mobile ? 'stretch' : 'flex-start',
      justifyContent: 'space-between',
      gap: 14,
      minWidth: 0,
    } satisfies CSSProperties,
    sectionTitle: {
      margin: 0,
      fontSize: mobile ? 18 : 19,
      fontWeight: 700,
      lineHeight: 1.25,
    } satisfies CSSProperties,
    sectionText: {
      margin: 0,
      fontSize: 14,
      lineHeight: 1.65,
      color: tokens.textMuted,
    } satisfies CSSProperties,
    mutedText: {
      margin: 0,
      fontSize: 14,
      lineHeight: 1.65,
      color: tokens.textMuted,
    } satisfies CSSProperties,
    subtleText: {
      margin: 0,
      fontSize: 12,
      lineHeight: 1.55,
      color: tokens.textSubtle,
      wordBreak: 'break-word',
    } satisfies CSSProperties,
    monoText: {
      margin: 0,
      fontSize: 13,
      color: tokens.textMuted,
      fontFamily: tokens.fontMono,
      fontVariantNumeric: 'tabular-nums',
      overflowWrap: 'anywhere',
    } satisfies CSSProperties,
    split: {
      display: 'grid',
      gap: compact ? 16 : 20,
      gridTemplateColumns: mobile ? '1fr' : compact ? 'repeat(auto-fit, minmax(260px, 1fr))' : 'repeat(auto-fit, minmax(300px, 1fr))',
      minWidth: 0,
    } satisfies CSSProperties,
    triple: {
      display: 'grid',
      gap: compact ? 16 : 20,
      gridTemplateColumns: mobile ? '1fr' : compact ? 'repeat(auto-fit, minmax(220px, 1fr))' : 'repeat(auto-fit, minmax(260px, 1fr))',
      minWidth: 0,
    } satisfies CSSProperties,
    infoCard: {
      display: 'flex',
      flexDirection: 'column',
      gap: 10,
      padding: compact ? 16 : 18,
      borderRadius: mobile ? 18 : 20,
      background: tokens.surfaceMuted,
      minWidth: 0,
    } satisfies CSSProperties,
    infoTitle: {
      margin: 0,
      fontSize: 15,
      fontWeight: 700,
    } satisfies CSSProperties,
    actionGrid: {
      display: 'grid',
      gap: 12,
      gridTemplateColumns: mobile ? '1fr' : 'repeat(auto-fit, minmax(220px, 1fr))',
    } satisfies CSSProperties,
    actionCard: {
      display: 'flex',
      flexDirection: 'column',
      gap: 10,
      padding: compact ? 16 : 18,
      borderRadius: mobile ? 18 : 20,
      background: tokens.surfaceMuted,
      minHeight: mobile ? 0 : 136,
      minWidth: 0,
    } satisfies CSSProperties,
    actionTitle: {
      margin: 0,
      fontSize: 15,
      fontWeight: 700,
    } satisfies CSSProperties,
    actionText: {
      margin: 0,
      fontSize: 13,
      lineHeight: 1.6,
      color: tokens.textMuted,
      flex: 1,
    } satisfies CSSProperties,
    toolbar: {
      display: 'flex',
      flexDirection: mobile ? 'column' : 'row',
      flexWrap: 'wrap',
      gap: 12,
      alignItems: mobile ? 'stretch' : 'center',
      justifyContent: 'space-between',
      minWidth: 0,
    } satisfies CSSProperties,
    toolbarGroup: {
      display: 'flex',
      flexDirection: mobile ? 'column' : 'row',
      flexWrap: 'wrap',
      gap: 10,
      alignItems: mobile ? 'stretch' : 'center',
      minWidth: 0,
      width: mobile ? '100%' : 'auto',
    } satisfies CSSProperties,
    searchField: {
      width: mobile ? '100%' : 'min(320px, 100%)',
    } satisfies CSSProperties,
    responsiveField: {
      width: mobile ? '100%' : 'min(280px, 100%)',
      minWidth: 0,
    } satisfies CSSProperties,
    list: {
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
      minWidth: 0,
    } satisfies CSSProperties,
    listItem: {
      display: 'flex',
      flexDirection: mobile ? 'column' : 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 16,
      padding: compact ? 14 : 16,
      borderRadius: mobile ? 16 : 18,
      background: tokens.surfaceMuted,
      minWidth: 0,
    } satisfies CSSProperties,
    listItemBody: {
      display: 'flex',
      flexDirection: 'column',
      gap: 8,
      minWidth: 0,
      flex: 1,
    } satisfies CSSProperties,
    listItemTitle: {
      margin: 0,
      fontSize: 15,
      fontWeight: 700,
      lineHeight: 1.45,
      wordBreak: 'break-word',
    } satisfies CSSProperties,
    listItemMeta: {
      margin: 0,
      fontSize: 12,
      lineHeight: 1.55,
      color: tokens.textSubtle,
      wordBreak: 'break-word',
    } satisfies CSSProperties,
    rowActions: {
      display: 'flex',
      flexDirection: mobile ? 'column' : 'row',
      flexWrap: 'wrap',
      gap: 8,
      alignItems: mobile ? 'stretch' : 'center',
      justifyContent: mobile ? 'flex-start' : 'flex-end',
      width: mobile ? '100%' : 'auto',
      minWidth: 0,
    } satisfies CSSProperties,
    tableWrap: {
      overflowX: 'auto',
      WebkitOverflowScrolling: 'touch',
      borderRadius: mobile ? 18 : 20,
      background: tokens.surfaceMuted,
      minWidth: 0,
    } satisfies CSSProperties,
    table: {
      width: '100%',
      borderCollapse: 'collapse',
      minWidth: compact ? 760 : 920,
    } satisfies CSSProperties,
    tableHead: {
      textAlign: 'left',
      fontSize: 12,
      color: tokens.textSubtle,
      fontWeight: 700,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      padding: compact ? '12px 14px' : '14px 16px',
      whiteSpace: 'nowrap',
      verticalAlign: 'top',
    } satisfies CSSProperties,
    tableCell: {
      padding: compact ? '14px' : '16px',
      fontSize: 14,
      lineHeight: 1.55,
      color: tokens.text,
      verticalAlign: 'top',
      minWidth: 0,
      maxWidth: compact ? 300 : 360,
      overflowWrap: 'anywhere',
    } satisfies CSSProperties,
    tableCellMuted: {
      color: tokens.textMuted,
    } satisfies CSSProperties,
    tableCellCompact: {
      fontSize: 13,
    } satisfies CSSProperties,
    dividerRow: {
      borderTop: `1px solid ${tokens.background}`,
    } satisfies CSSProperties,
    formGrid: {
      display: 'grid',
      gap: 14,
      gridTemplateColumns: mobile ? '1fr' : 'repeat(auto-fit, minmax(220px, 1fr))',
      minWidth: 0,
    } satisfies CSSProperties,
    fieldStack: {
      display: 'flex',
      flexDirection: 'column',
      gap: 8,
      minWidth: 0,
    } satisfies CSSProperties,
    inlineForm: {
      display: 'flex',
      flexDirection: mobile ? 'column' : 'row',
      flexWrap: 'wrap',
      gap: 10,
      alignItems: mobile ? 'stretch' : 'flex-end',
      minWidth: 0,
    } satisfies CSSProperties,
    note: {
      margin: 0,
      padding: compact ? 12 : 14,
      borderRadius: 16,
      background: tokens.surfaceMuted,
      fontSize: 13,
      lineHeight: 1.6,
      color: tokens.textMuted,
    } satisfies CSSProperties,
    codeBlock: {
      margin: 0,
      padding: compact ? 12 : 14,
      borderRadius: 16,
      background: tokens.surfaceMuted,
      fontSize: 13,
      lineHeight: 1.7,
      color: tokens.textMuted,
      fontFamily: tokens.fontMono,
      whiteSpace: 'pre-wrap',
      wordBreak: 'break-word',
    } satisfies CSSProperties,
    pagination: {
      display: 'flex',
      flexDirection: mobile ? 'column' : 'row',
      flexWrap: 'wrap',
      alignItems: mobile ? 'stretch' : 'center',
      justifyContent: 'space-between',
      gap: 12,
    } satisfies CSSProperties,
    tagRow: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: 8,
      alignItems: 'center',
    } satisfies CSSProperties,
    errorText: {
      margin: 0,
      fontSize: 13,
      lineHeight: 1.6,
      color: tokens.danger,
    } satisfies CSSProperties,
  };
}
