"""add criteria promt

Revision ID: 4215a3864fe3
Revises: 795478320c34
Create Date: 2026-03-29 19:44:07.896147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4215a3864fe3'
down_revision: Union[str, Sequence[str], None] = '795478320c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('promt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criteria', 'promt')
    # ### end Alembic commands ###
